name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - "python-version/**"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "python-version/**"
      - ".github/workflows/python-ci.yml"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-version

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install linting dependencies
        run: |
          uv pip install ruff black mypy

      - name: Lint with ruff
        run: ruff check .

      - name: Format check with black
        run: black --check .

      - name: Type check with mypy
        run: mypy .

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-version

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install pytest pytest-asyncio httpx

      - name: Run tests
        run: pytest

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./python-version

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install k6-python

      - name: Start server
        run: |
          python -m uvicorn main:app --host 0.0.0.0 --port 3000 --workers 1 &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
          # Give the server time to start
          sleep 3

      - name: Install k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-linux-amd64.tar.gz | tar xz
          sudo mv k6-v0.46.0-linux-amd64/k6 /usr/local/bin/

      - name: Run basic load test
        run: k6 run --vus 1 --duration 3s loadtest.js

      - name: Stop server
        if: always()
        run: kill $SERVER_PID
